apiVersion: v1
kind: ConfigMap
metadata:
  name: zero-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_NAME: "jdbc:postgresql://postgresdb:5432/storage"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SERVER_PORT: "8080"
